version: "3"
services:
  flask:
    build: ./
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./:/var/fruitfacts
    ports:
      - 33008:80
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fruitfacts
      MONGO_INITDB_ROOT_PASSWORD: fruitfacts

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fruitfacts
      ME_CONFIG_MONGODB_ADMINPASSWORD: fruitfacts