version: '3.3'
services:
  service:
    build: .
    restart: always
    read_only: true
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.1'
          memory: 100m
    ports:
      - "33701:1337"